### PR TITLE
414 xrefstyle support

### PR DESCRIPTION
**Pull request by fsteimke**
Support for `xref/@xrefstyle` as requested in issue #414 is described in a new Section _2.9: Customize individual cross references_ in the Reference manual. Please be so kind to check the text of this new section, since my knowledge of the english language is not good at all.

I have also tried to implement an page-number reference e. g. see _page xxx_ with the `%p` template. I hope the solution meets your expectations. Please have a look at links.xsl around line 242.

### CODE REVIEW

**Comment by ndw** [comment]
I will follow-up on this asap. Jammed up with other things just at the moment.

**Comment by ndw** [comment]
Thank you, Frank! I've reworked your patch a little bit in PR #446 which I'll merge momentarily.

I'm sorry I've been so slow to respond to these. *A lot* has been going on. But I hope to get on top of all of them over the coming week or so. Thank you for your contributions!

**Comment by fsteimke** [comment]
No problem at all. I can understand that you have a lot on your mind at the moment - it's only been a few days since I read the announcement in saxon diaries about the change at the top of Saxonica. Congratulations on your new position as CEO.

I am therefore delighted with the positive feedback and feel proud to be making some contributions to the further development of xslTNG.

**Comment by ndw** [comment]
You're making great contributions and I really appreciate it.

**Pull request closed without merging**
