### PR TITLE
Add parameter to control resolving object URIs

### PR DESCRIPTION
**Pull request by tigloo**
Here is a pull request proposing a fix for #89 

I'm really bad with XSL and also not a native speaker, so this most likely requires careful review. I used the recently added generate-html-page parameter as a reference for the required changes.

### CODE REVIEW

**Comment by ndw** [comment]
Did my suggestion in #89 on 16 February work for you? On reading through this issue again, I feel I may have misunderstood. If it did work for you, that's great, just let me know. If it didn't, I'll see if I now have a better understanding of the problem and can help fix it.

**Comment by tigloo** [comment]
Thanks for following-up, in fact I'm still using my patch but simply because 1.4.0 was not released and I required another change that wasn't part of 1.3.1.

I still believe the proposed change would make sense when working with paths that don't exist at processing time. For example, in my case images are served from an API URL. The API URL doesn't exist in the filesystem as a directory. I coincidentally use the API's URL path as directory when creating the HTML and corresponding image assets, but this may not be the case for everyone.

On the other hand, I agree that the proposed fix overlaps with being able to set the base URL manually and (for me) setting the base URL instead should just work fine.

**Comment by ndw** [comment]
Okay. I think I understand the problem a little better. Let me give it some thought.

One reason to resolve the `@fileref` values during the transformation is so that the extension functions that compute things like the image dimensions can find the images. Do the `@fileref` values in your documents "just work" because they have the correct relative paths, or do you not use the extension function features?

**Comment by tigloo** [comment]
I only use the fileref attribute to point to the image. My use case is the following: I'm translating documents from different XML formats to Docbook. Docbook is my common intermediate format and from Docbook I'm generating HTML, separate table of contents, keyword dictionaries for search, etc.

In all my inputs, images have a unique name per document. I put the unique name into the fileref attribute and prepend the API retrieval path ("assets"). So when that path ends up in the HTML img src attribute, the browser will request the unique image name from the API and I can serve it to the client.

Since I'm coincidentally recreating that directory structure during pre-processing, I can look at the intermediate Docbook file in an XML viewer and it displays fine.

**Pull request closed without merging**
